services:
  app:
    build:
      context: .
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: dpg-csnhmnij1k6c73b3ljqg-a
      DB_PORT: 5432
      DB_DATABASE: acelaravel
      DB_USERNAME: acelaravel_user
      DB_PASSWORD: "zJpicnos76KVcURUuOFUuIRf8ltSbUz8"
      PORT: 10000  
      ports:
      - "${PORT}:${PORT}" 
    volumes:
      - .:/var/www
